#![deny(warnings)]

use warp::Filter;

/// Generated by PROST!
mod user_proto {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UserRequest {
        #[prost(string, tag = "1")]
        pub username: std::string::String,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct UserResponse {
        #[prost(uint64, tag = "1")]
        pub id: u64,
    }
}

// Don't copy this `cfg`, its only needed because this file is within
// the warp repository.
#[cfg(feature = "proto")]
#[tokio::main]
async fn main() {
    pretty_env_logger::init();

    let hello_user = warp::post()
        .and(warp::path("user"))
        .and(warp::body::content_length_limit(1024 * 16))
        .and(warp::body::proto())
        .map(|user: user_proto::UserRequest| format!("Hello {}!", user.username));

    warp::serve(hello_user).run(([127, 0, 0, 1], 3030)).await

    /*  Test this with cURL
        $ cd <directory where warp is cloned>
        $ echo "username:'Jillian'" | \
            protoc --encode user.UserRequest "./examples/proto/user.proto" | \
            curl -X POST --data-binary @- http://localhost:3030/user
    */
}

#[cfg(not(feature = "proto"))]
fn main() {
    eprintln!("Requires the `proto` feature.");
}
